package com.platform.dentify.inventory.domain.model.valueobjects;

public enum ItemCategory {
    DENTAL_INSTRUMENTS,
    DISPOSABLE_SUPPLIES,
    CLEANING_AND_DISINFECTION,
    RESTORATIVE_MATERIALS,
    ORTHODONTIC_SUPPLIES,
    ENDODONTIC_SUPPLIES,
    SURGICAL_SUPPLIES,
    PROTECTIVE_EQUIPMENT,
    IMAGING_EQUIPMENT,
    CONSUMABLES,
    MEDICATIONS
}
